#!/bin/sh
set -e

echo "Activating feature 'shell-enhancements'"

# Create the aliases file
ALIASES_FILE="/usr/local/share/shell-enhancements.sh"

cat > "$ALIASES_FILE" << 'EOF'
#!/bin/bash
# Shell Enhancements - Generated by devcontainer feature

# Safety aliases
alias rm='rm -i'
alias cp='cp -i'  
alias mv='mv -i'

# Better defaults
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# System info shortcuts  
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias ps='ps aux'
alias top='htop 2>/dev/null || top'

# Network shortcuts
alias ports='netstat -tuln'
alias ping='ping -c 5'
alias wget='wget -c'

# File operations
alias mkdir='mkdir -pv'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Quick edit
alias bashrc='${EDITOR:-nano} ~/.bashrc'
alias zshrc='${EDITOR:-nano} ~/.zshrc'

# Development helpers
alias serve='python3 -m http.server 8000'
alias jsonpp='python3 -m json.tool'
alias urlencode='python3 -c "import sys, urllib.parse as ul; print(ul.quote_plus(sys.argv[1]))"'
alias urldecode='python3 -c "import sys, urllib.parse as ul; print(ul.unquote_plus(sys.argv[1]))"'

# Find shortcuts
alias ff='find . -type f -name'
alias fd='find . -type d -name'

# Git shortcuts (if git is available)
if command -v git > /dev/null 2>&1; then
    alias g='git'
    alias gs='git status'
    alias gd='git diff'
    alias ga='git add'
    alias gc='git commit'
    alias gp='git push'
    alias gl='git pull'
fi

# Useful functions
mkcd() {
    mkdir -p "$1" && cd "$1"
}

extract() {
    if [ -f "$1" ]; then
        case "$1" in
            *.tar.bz2)   tar xjf "$1"     ;;
            *.tar.gz)    tar xzf "$1"     ;;
            *.bz2)       bunzip2 "$1"     ;;
            *.rar)       unrar x "$1"     ;;
            *.gz)        gunzip "$1"      ;;
            *.tar)       tar xf "$1"      ;;
            *.tbz2)      tar xjf "$1"     ;;
            *.tgz)       tar xzf "$1"     ;;
            *.zip)       unzip "$1"       ;;
            *.Z)         uncompress "$1"  ;;
            *.7z)        7z x "$1"        ;;
            *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

backup() {
    cp "$1"{,.bak}
}

# Process management
psg() {
    ps aux | grep -v grep | grep "$@" -i --color=auto
}

# Weather function (requires curl)
weather() {
    curl -s "wttr.in/${1:-}?format=3"
}

EOF

# Add color output if enabled
if [ "${INCLUDECOLOROUTPUT}" = "true" ]; then
    cat >> "$ALIASES_FILE" << 'EOF'

# Colorized output
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
fi

EOF
fi

# Add directory aliases if enabled  
if [ "${INCLUDEDIRECTORYALIASES}" = "true" ]; then
    cat >> "$ALIASES_FILE" << 'EOF'

# Directory shortcuts
alias desk='cd ~/Desktop 2>/dev/null || cd ~'
alias docs='cd ~/Documents 2>/dev/null || cd ~'  
alias downloads='cd ~/Downloads 2>/dev/null || cd ~'
alias projects='cd ~/projects 2>/dev/null || mkdir -p ~/projects && cd ~/projects'
alias workspace='cd /workspace 2>/dev/null || cd ~'

EOF
fi

# Add Docker aliases if enabled
if [ "${INCLUDEDOCKERALIASES}" = "true" ]; then
    cat >> "$ALIASES_FILE" << 'EOF'

# Docker shortcuts (if docker is available)
if command -v docker > /dev/null 2>&1; then
    alias d='docker'
    alias dc='docker-compose'
    alias dps='docker ps'
    alias di='docker images'
    alias dex='docker exec -it'
    alias dlogs='docker logs -f'
    alias dclean='docker system prune -f'
    alias dcup='docker-compose up -d'
    alias dcdown='docker-compose down'
    alias dcrestart='docker-compose restart'
fi

EOF
fi

# Configure based on shell preference
if [ "${SHELL}" = "bash" ] || [ "${SHELL}" = "both" ]; then
    echo "source $ALIASES_FILE" >> /etc/bash.bashrc
    # Also add to root's bashrc for when running as root
    echo "source $ALIASES_FILE" >> ~/.bashrc 2>/dev/null || true
fi

if [ "${SHELL}" = "zsh" ] || [ "${SHELL}" = "both" ]; then
    echo "source $ALIASES_FILE" >> /etc/zsh/zshrc 2>/dev/null || true
    # Also add to root's zshrc  
    echo "source $ALIASES_FILE" >> ~/.zshrc 2>/dev/null || true
fi

# Create info command
cat > /usr/local/bin/shell-help << 'EOF'
#!/bin/sh
echo "🚀 Shell Enhancements Installed!"
echo ""
echo "📁 Directory Navigation:"
echo "  ll, la, l     - ls variations"
echo "  .., ..., .... - cd up directories"  
echo "  mkcd <dir>    - mkdir and cd"
echo ""
echo "🔧 File Operations:"
echo "  ff <name>     - find files"
echo "  fd <name>     - find directories"
echo "  extract <file> - extract archives"
echo "  backup <file> - create .bak copy"
echo ""
echo "💻 Development:"
echo "  serve         - python http server on port 8000"
echo "  jsonpp        - pretty print JSON"
echo "  weather [city] - get weather info"
echo ""
echo "🐳 Git & Docker shortcuts available if tools are installed"
echo ""
echo "Run 'alias' to see all available aliases"
EOF

chmod +x /usr/local/bin/shell-help

echo "Shell enhancements installed! Run 'shell-help' for more info."